version: "3.8"
services:
  odoo:
    build: .
    container_name: odoo17
    depends_on:
      - db
    ports:
      - "8090:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo.conf
    command: ["--config=/etc/odoo.conf"]
    networks:
      - odoo-net
      
  db:
    image: postgres:15
    container_name: odoo17-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - odoo-net
      
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - odoo-net
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  odoo-data:
  db-data:
  pgadmin-data:

networks:
  odoo-net:
